steps:
  - name: ':docker: :package:'
    plugins:
      'docker-compose#v1.8.4':
        build: fusion-plugin-test-only
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - command: yarn flow
    name: ':flowtype:'
    plugins:
      'docker-compose#v1.8.4':
        run: fusion-plugin-test-only
    agents:
      queue: workers
  - name: ':eslint:'
    command: yarn lint
    plugins:
      'docker-compose#v1.8.4':
        run: fusion-plugin-test-only
    agents:
      queue: workers
  - name: ':chrome: :white_check_mark:'
    command: .buildkite/browserTests
    plugins:
      'docker-compose#v1.8.4':
        run: fusion-plugin-test-only
    agents:
      queue: workers
  - name: ':node: :white_check_mark:'
    command: .buildkite/nodeTests
    plugins:
      'docker-compose#v1.8.4':
        run: fusion-plugin-test-only
    agents:
      queue: workers
